// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.grpcProject;

public interface BookRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BookRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string book_id = 1;</code>
   * @return The bookId.
   */
  java.lang.String getBookId();
  /**
   * <code>string book_id = 1;</code>
   * @return The bytes for bookId.
   */
  com.google.protobuf.ByteString
      getBookIdBytes();
}
