// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.grpcProject;

public interface BookResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BookResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string book_id = 1;</code>
   * @return The bookId.
   */
  java.lang.String getBookId();
  /**
   * <code>string book_id = 1;</code>
   * @return The bytes for bookId.
   */
  com.google.protobuf.ByteString
      getBookIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.Type type = 3;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.Type type = 3;</code>
   * @return The type.
   */
  com.grpcProject.Type getType();
}
