// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.grpcProject;

public final class Schema {
  private Schema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014schema.proto\032\nutil.proto\"\036\n\013BookReques" +
      "t\022\017\n\007book_id\030\001 \001(\t\"B\n\014BookResponse\022\017\n\007bo" +
      "ok_id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\023\n\004type\030\003 \001(\0162" +
      "\005.Type27\n\013BookService\022(\n\007getBook\022\014.BookR" +
      "equest\032\r.BookResponse\"\000B\023\n\017com.grpcProje" +
      "ctP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.grpcProject.Util.getDescriptor(),
        });
    internal_static_BookRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookRequest_descriptor,
        new java.lang.String[] { "BookId", });
    internal_static_BookResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BookResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookResponse_descriptor,
        new java.lang.String[] { "BookId", "Name", "Type", });
    com.grpcProject.Util.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
