// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: util.proto

package com.grpcProject;

public final class Util {
  private Util() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nutil.proto*3\n\004Type\022\013\n\007FANTASY\020\000\022\021\n\rAUT" +
      "OBIOGRAPHY\020\001\022\013\n\007HISTORY\020\002B\023\n\017com.grpcPro" +
      "jectP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
